@echo off
echo Inicializando repositorio...
git init
echo Configurando usuario...
git config user.name "CodeByDante"
git config user.email "codebydante@users.noreply.github.com"
echo Añadiendo archivos...
git add .
echo Committing...
git commit -m "feat: Update Project via Agent"
echo Configurando rama y remote...
git branch -M main
git remote remove origin
git remote add origin https://github.com/CodeByDante/twisted-brody-MangaFlow.git
echo Intentando push (puede requerir autenticacion)...
git push -u origin main --force
pause
